//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace talYBProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class costomerTBL
    {
        public int Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string companyName { get; set; }
        public string address { get; set; }
        public string cellPhone { get; set; }
        public string phone1 { get; set; }
        public string officePhone { get; set; }
        public string email { get; set; }
        public int price { get; set; }
        public string notes { get; set; }
        public string fullName { get; set; }
    }
}
