//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace talYBProj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<costomerTBL> costomerTBL { get; set; }
        public virtual DbSet<oilTBL> oilTBL { get; set; }
        public virtual DbSet<oliveTBL> oliveTBL { get; set; }
        public virtual DbSet<orderTBL> orderTBL { get; set; }
        public virtual DbSet<packTBL> packTBL { get; set; }
        public virtual DbSet<userTBL> userTBL { get; set; }
        public virtual DbSet<zanTBL> zanTBL { get; set; }
        public virtual DbSet<customerView> customerView { get; set; }
        public virtual DbSet<zanView> zanView { get; set; }
        public virtual DbSet<orderView> orderView { get; set; }
    }
}
