//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace talYBProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class oilTBL
    {
        public int Id { get; set; }
        public int orderID { get; set; }
        public int PackID { get; set; }
        public int quantity { get; set; }
        public System.DateTime currDate { get; set; }
        public string notes { get; set; }
        public int userID { get; set; }
    
        public virtual orderTBL orderTBL { get; set; }
        public virtual packTBL packTBL { get; set; }
        public virtual userTBL userTBL { get; set; }
    }
}
