//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace talYBProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orderTBL()
        {
            this.oilTBL = new HashSet<oilTBL>();
            this.oliveTBL = new HashSet<oliveTBL>();
            this.zanTBL1 = new HashSet<zanTBL>();
        }
    
        public int Id { get; set; }
        public string orderDate { get; set; }
        public int zanID { get; set; }
        public int numOfDolevim { get; set; }
        public bool isDone { get; set; }
        public bool isPayd { get; set; }
        public int userID { get; set; }
        public string notes { get; set; }
        public int totalPayment { get; set; }
        public int totalOlive { get; set; }
        public int totalOil { get; set; }
        public int numOfOiPacks { get; set; }
        public int orderPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oilTBL> oilTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oliveTBL> oliveTBL { get; set; }
        public virtual userTBL userTBL { get; set; }
        public virtual zanTBL zanTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zanTBL> zanTBL1 { get; set; }
    }
}
