//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace talYBProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderView
    {
        public int id { get; set; }
        public string custName { get; set; }
        public string custPhone { get; set; }
        public System.DateTime orderDate { get; set; }
        public int customerID { get; set; }
        public string zanName { get; set; }
        public Nullable<int> totalDolavWeight { get; set; }
        public Nullable<int> totalOilWeight { get; set; }
        public double price { get; set; }
        public Nullable<double> totalPackPrice { get; set; }
        public Nullable<double> totalDebt { get; set; }
        public bool isPayd { get; set; }
    }
}
