//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace talYBProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderTBL
    {
        public int Id { get; set; }
        public string orderDate { get; set; }
        public Nullable<int> zanID { get; set; }
        public Nullable<int> numOfDolevim { get; set; }
        public Nullable<bool> isDone { get; set; }
        public Nullable<bool> isPayd { get; set; }
        public Nullable<int> userID { get; set; }
        public string notes { get; set; }
        public Nullable<int> totalPayment { get; set; }
        public Nullable<int> totalOlive { get; set; }
        public Nullable<int> totalOil { get; set; }
        public Nullable<int> numOfOiPacks { get; set; }
        public Nullable<int> orderPrice { get; set; }
    }
}
