//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace talYBProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class packTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public packTBL()
        {
            this.oilTBL = new HashSet<oilTBL>();
        }
    
        public int Id { get; set; }
        public int weight { get; set; }
        public int price { get; set; }
        public string notes { get; set; }
        public int userID { get; set; }
        public System.DateTime date { get; set; }
        public int dolevNum { get; set; }
        public int orderID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oilTBL> oilTBL { get; set; }
    }
}
